"""
Text Sanitizer Service.

Ensures all text generated by LLMs or passed to Text-to-Speech (TTS) engines
is clean plain text — strictly stripping emojis, logos, emoticons, markdown formatting,
bullet points, and special symbols that cause unnatural speech synthesizer artifacts.
"""
import re

# Strict directive appended to LLM system prompts
PLAIN_TEXT_SPEECH_DIRECTIVE = (
    "CRITICAL FORMATTING RULE: Your response will be spoken aloud directly by a real-time Text-to-Speech (TTS) avatar. "
    "You MUST respond ONLY in pure, natural plain text. "
    "Strictly NEVER include emojis, emoticons, logos, ASCII art, markdown asterisks (no **bold** or *italic*), "
    "bullet points, numbered lists, headers (#), or special symbols under any circumstance."
)

# Comprehensive regex matching emojis, pictographs, symbols, dingbats, logos, and modifiers
_EMOJI_PATTERN = re.compile(
    "["
    "\U0001F600-\U0001F64F"  # Emoticons
    "\U0001F300-\U0001F5FF"  # Misc Symbols and Pictographs
    "\U0001F680-\U0001F6FF"  # Transport and Map
    "\U0001F1E0-\U0001F1FF"  # Flags
    "\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
    "\U0001FA00-\U0001FA6F"  # Chess Symbols, Symbols Extended-A
    "\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-B
    "\U00002600-\U000026FF"  # Misc symbols (⚡, ✈, ☕, ⚠️, ❄, etc.)
    "\U00002700-\U000027BF"  # Dingbats (✨, ✂, ✉, etc.)
    "\U00002300-\U000023FF"  # Misc Technical (⏱, ⌛, etc.)
    "\U00002B00-\U00002BFF"  # Misc Symbols and Arrows
    "\U000025A0-\U000025FF"  # Geometric Shapes (■, ●, etc.)
    "\U0000200D"              # Zero Width Joiner (used in composite emojis)
    "\uFE0E\uFE0F"            # Variation Selectors
    "\U0001F000-\U0001F02F"  # Mahjong
    "\U0001F0A0-\U0001F0FF"  # Playing cards
    "\uf8ff"                  # Apple logo / Private use
    "\u2022\u25BA\u25AA\u25AB"# Bullet characters (•, ►, ▪, ▫)
    "™®©"                     # Common trademark/copyright symbols
    "]+",
    flags=re.UNICODE,
)


def clean_text_for_speech(text: str) -> str:
    """
    Sanitize text for natural Text-to-Speech reading.

    1. Removes markdown code blocks and inline code ticks.
    2. Converts markdown links [text](url) -> text.
    3. Strips markdown bold, italic, strikethrough delimiters.
    4. Removes markdown headers and bullet prefixes.
    5. Strips all Unicode emojis, logos, dingbats, and symbol characters.
    6. Normalizes whitespace and line breaks.

    Args:
        text: Raw input or LLM generated response string.

    Returns:
        Cleaned, plain conversational text ready for audio synthesis.
    """
    if not text:
        return ""

    # 1. Remove fenced code blocks completely
    text = re.sub(r"```[\s\S]*?```", "", text)

    # 2. Strip inline code ticks `code` -> code
    text = re.sub(r"`([^`]+)`", r"\1", text)

    # 3. Convert markdown links [Label](url) -> Label
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)

    # 4. Strip markdown bold / italic / strikethrough delimiters (**text**, *text*, __text__, _text_, ~~text~~)
    text = re.sub(r"(\*\*|__)(.*?)\1", r"\2", text)
    text = re.sub(r"(\*|_)(.*?)\1", r"\2", text)
    text = re.sub(r"~~(.*?)~~", r"\1", text)

    # 5. Remove markdown headers (# Title -> Title)
    text = re.sub(r"^\s*#{1,6}\s*", "", text, flags=re.MULTILINE)

    # 6. Remove bullet markers at line starts (- item, * item, + item, • item, 1. item)
    text = re.sub(r"^\s*(?:[-*+•►▪▫]|\d+\.)\s+", "", text, flags=re.MULTILINE)

    # 7. Strip all emojis, pictographs, dingbats, logos, and special symbols
    text = _EMOJI_PATTERN.sub("", text)

    # 8. Normalize whitespace and newlines
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n\s*\n+", " ", text)
    text = re.sub(r"\n", " ", text)

    return text.strip()
